In [37]:
pip install pandas

Requirement already satisfied: pandas in c:\users\mange\appdata\local\programs\python\python313\lib\site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\mange\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.2.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\mange\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\mange\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\mange\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\mange\appdata\local\programs\python\python313\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0.1 -> 25.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [38]:
import pandas as pd

In [39]:
import numpy as np

In [40]:
df=pd.read_csv("dataset_Facebook.csv",delimiter=';')

In [41]:
df

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
0,139441,Photo,2,12,4,3,0.0,2752,5091,178,109,159,3078,1640,119,4,79.0,17.0,100
1,139441,Status,2,12,3,10,0.0,10460,19057,1457,1361,1674,11710,6112,1108,5,130.0,29.0,164
2,139441,Photo,3,12,3,3,0.0,2413,4373,177,113,154,2812,1503,132,0,66.0,14.0,80
3,139441,Photo,2,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048,1386,58,1572.0,147.0,1777
4,139441,Photo,2,12,2,3,0.0,7244,13594,671,410,580,6228,3200,396,19,325.0,49.0,393
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,85093,Photo,3,1,7,2,0.0,4684,7536,733,708,985,4750,2876,392,5,53.0,26.0,84
496,81370,Photo,2,1,5,8,0.0,3480,6229,537,508,687,3961,2104,301,0,53.0,22.0,75
497,81370,Photo,1,1,5,2,0.0,3778,7216,625,572,795,4742,2388,363,4,93.0,18.0,115
498,81370,Photo,3,1,4,11,0.0,4156,7564,626,574,832,4534,2452,370,7,91.0,38.0,136
499,81370,Photo,2,1,4,4,NaN,4188,7292,564,524,743,3861,2200,316,0,91.0,28.0,119

In [42]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 19 columns):
 #   Column                                                               Non-Null Count  Dtype
---  ------                                                               --------------  -----
 0   Page total likes                                                     500 non-null    int64
 1   Type                                                                 500 non-null    object
 2   Category                                                             500 non-null    int64
 3   Post Month                                                           500 non-null    int64
 4   Post Weekday                                                         500 non-null    int64
 5   Post Hour                                                            500 non-null    int64
 6   Paid                                                                 499 non-null    float64
 7   Lifetime Post Total Reach                                            500 non-null    int64
 8   Lifetime Post Total Impressions                                      500 non-null    int64
 9   Lifetime Engaged Users                                               500 non-null    int64
 10  Lifetime Post Consumers                                              500 non-null    int64
 11  Lifetime Post Consumptions                                           500 non-null    int64
 12  Lifetime Post Impressions by people who have liked your Page         500 non-null    int64
 13  Lifetime Post reach by people who like your Page                     500 non-null    int64
 14  Lifetime People who have liked your Page and engaged with your post  500 non-null    int64
 15  comment                                                              500 non-null    int64
 16  like                                                                 499 non-null    float64
 17  share                                                                496 non-null    float64
 18  Total Interactions                                                   500 non-null    int64
dtypes: float64(3), int64(15), object(1)
memory usage: 74.3+ KB

In [43]:
df.describe()

,Page total likes,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
count,500.000000,500.000000,500.000000,500.000000,500.000000,499.000000,500.00000,5.000000e+02,500.000000,500.000000,500.000000,5.000000e+02,500.000000,500.000000,500.00000,499.000000,496.000000,500.000000
mean,123194.176000,1.880000,7.038000,4.150000,7.840000,0.278557,13903.36000,2.958595e+04,920.344000,798.772000,1415.130000,1.676638e+04,6585.488000,609.986000,7.48200,177.945892,27.266129,212.120000
std,16272.813214,0.852675,3.307936,2.030701,4.368589,0.448739,22740.78789,7.680325e+04,985.016636,882.505013,2000.594118,5.979102e+04,7682.009405,612.725618,21.18091,323.398742,42.613292,380.233118
min,81370.000000,1.000000,1.000000,1.000000,1.000000,0.000000,238.00000,5.700000e+02,9.000000,9.000000,9.000000,5.670000e+02,236.000000,9.000000,0.00000,0.000000,0.000000,0.000000
25%,112676.000000,1.000000,4.000000,2.000000,3.000000,0.000000,3315.00000,5.694750e+03,393.750000,332.500000,509.250000,3.969750e+03,2181.500000,291.000000,1.00000,56.500000,10.000000,71.000000
50%,129600.000000,2.000000,7.000000,4.000000,9.000000,0.000000,5281.00000,9.051000e+03,625.500000,551.500000,851.000000,6.255500e+03,3417.000000,412.000000,3.00000,101.000000,19.000000,123.500000
75%,136393.000000,3.000000,10.000000,6.000000,11.000000,1.000000,13168.00000,2.208550e+04,1062.000000,955.500000,1463.000000,1.486050e+04,7989.000000,656.250000,7.00000,187.500000,32.250000,228.500000
max,139441.000000,3.000000,12.000000,7.000000,23.000000,1.000000,180480.00000,1.110282e+06,11452.000000,11328.000000,19779.000000,1.107833e+06,51456.000000,4376.000000,372.00000,5172.000000,790.000000,6334.000000

In [44]:
df1=df[['Type','Category','like']].loc[0:20]

In [45]:
df1

      Type  Category    like
0    Photo         2    79.0
1   Status         2   130.0
2    Photo         3    66.0
3    Photo         2  1572.0
4    Photo         2   325.0
5   Status         2   152.0
6    Photo         3   249.0
7    Photo         3   325.0
8   Status         2   161.0
9    Photo         3   113.0
10  Status         2   233.0
11   Photo         2    88.0
12   Photo         2    90.0
13   Photo         2   137.0
14   Photo         2   577.0
15  Status         2    86.0
16   Photo         3    40.0
17   Photo         1   678.0
18  Status         3    54.0
19   Photo         3    34.0
20   Photo         2    66.0

In [47]:
df2=df[['Type','share','Category']].loc[20:40]

##

In [48]:
df2

      Type  share  Category
20   Photo   12.0         2
21   Photo    0.0         1
22    Link    2.0         1
23   Photo   24.0         3
24  Status   19.0         2
25  Status   18.0         2
26  Status   72.0         2
27   Photo   17.0         3
28   Photo   63.0         2
29   Video   13.0         1
30   Photo   22.0         2
31   Photo   11.0         2
32   Photo   47.0         3
33   Photo   23.0         3
34   Photo   17.0         1
35   Photo   21.0         2
36   Photo   17.0         3
37   Photo    8.0         1
38  Status   31.0         2
39   Photo   14.0         1
40  Status   39.0         2

In [49]:
merged_df=pd.merge(df1,df2,on=['Type','Category'],how='inner')

In [51]:
merged_df

     Type  Category  like  share
0   Photo         2  79.0   12.0
1   Photo         2  79.0   63.0
2   Photo         2  79.0   22.0
3   Photo         2  79.0   11.0
4   Photo         2  79.0   21.0
..    ...       ...   ...    ...
94  Photo         2  66.0   12.0
95  Photo         2  66.0   63.0
96  Photo         2  66.0   22.0
97  Photo         2  66.0   11.0
98  Photo         2  66.0   21.0

[99 rows x 4 columns]

In [54]:
df2.sort_values(by="share",ascending=True)

      Type  share  Category
21   Photo    0.0         1
22    Link    2.0         1
37   Photo    8.0         1
31   Photo   11.0         2
20   Photo   12.0         2
29   Video   13.0         1
39   Photo   14.0         1
34   Photo   17.0         1
27   Photo   17.0         3
36   Photo   17.0         3
25  Status   18.0         2
24  Status   19.0         2
35   Photo   21.0         2
30   Photo   22.0         2
33   Photo   23.0         3
23   Photo   24.0         3
38  Status   31.0         2
40  Status   39.0         2
32   Photo   47.0         3
28   Photo   63.0         2
26  Status   72.0         2

In [56]:
merged_df.transpose()

,0,1,2,3,4,5,6,7,8,9,...,89,90,91,92,93,94,95,96,97,98
Type,Photo,Photo,Photo,Photo,Photo,Status,Status,Status,Status,Status,...,Photo,Photo,Photo,Photo,Photo,Photo,Photo,Photo,Photo,Photo
Category,2,2,2,2,2,2,2,2,2,2,...,3,3,3,3,3,2,2,2,2,2
like,79.0,79.0,79.0,79.0,79.0,130.0,130.0,130.0,130.0,130.0,...,34.0,34.0,34.0,34.0,34.0,66.0,66.0,66.0,66.0,66.0
share,12.0,63.0,22.0,11.0,21.0,19.0,18.0,72.0,31.0,39.0,...,24.0,17.0,47.0,23.0,17.0,12.0,63.0,22.0,11.0,21.0

In [57]:
df.shape

(500, 19)

In [63]:
new=pd.melt(df,id_vars=['Type'],value_vars='like')
new

       Type variable   value
0     Photo     like    79.0
1    Status     like   130.0
2     Photo     like    66.0
3     Photo     like  1572.0
4     Photo     like   325.0
..      ...      ...     ...
495   Photo     like    53.0
496   Photo     like    53.0
497   Photo     like    93.0
498   Photo     like    91.0
499   Photo     like    91.0

[500 rows x 3 columns]

In [ ]:
grp=df.groupby(['Total Interactions'])['like'].sum().reset_index()

In [65]:
grp

     Total Interactions    like
0                     0     0.0
1                     2     6.0
2                     3     6.0
3                     4     5.0
4                     5     8.0
..                  ...     ...
275                1806  1639.0
276                1873  1546.0
277                1974  1622.0
278                2177  1998.0
279                6334  5172.0

[280 rows x 2 columns]

In [66]:
import seaborn as sns

ModuleNotFoundError: No module named 'seaborn'

In [ ]:
pip insta